// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk-szTgMpAglw4bHu9ZJ8V8JJsRYQPVMY',
    appId: '1:366516710495:web:e842bd09cd41d23560ffea',
    messagingSenderId: '366516710495',
    projectId: 'friendly-store-e7d7f',
    authDomain: 'friendly-store-e7d7f.firebaseapp.com',
    databaseURL: 'https://friendly-store-e7d7f-default-rtdb.firebaseio.com',
    storageBucket: 'friendly-store-e7d7f.appspot.com',
    measurementId: 'G-S0PQWVLDJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZkDMM_3BRPnoiMQnrYHTDVC9k2t0Cu-w',
    appId: '1:366516710495:android:0ce72aee736c1ab760ffea',
    messagingSenderId: '366516710495',
    projectId: 'friendly-store-e7d7f',
    databaseURL: 'https://friendly-store-e7d7f-default-rtdb.firebaseio.com',
    storageBucket: 'friendly-store-e7d7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq9MiDWMHKrXNwSCamviFEpI72EJzDI5U',
    appId: '1:366516710495:ios:38ac42d51d4c287960ffea',
    messagingSenderId: '366516710495',
    projectId: 'friendly-store-e7d7f',
    databaseURL: 'https://friendly-store-e7d7f-default-rtdb.firebaseio.com',
    storageBucket: 'friendly-store-e7d7f.appspot.com',
    iosClientId: '366516710495-ln2vgr6ns67td9hlpaodf971u6p05vo8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ver01Friendlystore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq9MiDWMHKrXNwSCamviFEpI72EJzDI5U',
    appId: '1:366516710495:ios:38ac42d51d4c287960ffea',
    messagingSenderId: '366516710495',
    projectId: 'friendly-store-e7d7f',
    databaseURL: 'https://friendly-store-e7d7f-default-rtdb.firebaseio.com',
    storageBucket: 'friendly-store-e7d7f.appspot.com',
    iosClientId: '366516710495-ln2vgr6ns67td9hlpaodf971u6p05vo8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ver01Friendlystore',
  );
}
