class Autogenerated {
  IntS? intS;

  Autogenerated({this.intS});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    intS = json['intS'] != null ? new IntS.fromJson(json['intS']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.intS != null) {
      data['intS'] = this.intS!.toJson();
    }
    return data;
  }
}

class IntS {
  String? youtube01;
  String? image;
  String? kcal;
  String? youtube02;
  String? youtube03;
  String? effect;
  String? keep;
  String? name;
  String? season;
  String? tip;
  int? idx;
  String? info;

  IntS(
      {this.youtube01,
      this.image,
      this.kcal,
      this.youtube02,
      this.youtube03,
      this.effect,
      this.keep,
      this.name,
      this.season,
      this.tip,
      this.idx,
      this.info});

  IntS.fromJson(Map<String, dynamic> json) {
    youtube01 = json['youtube01'];
    image = json['image'];
    kcal = json['kcal'];
    youtube02 = json['youtube02'];
    youtube03 = json['youtube03'];
    effect = json['effect'];
    keep = json['keep'];
    name = json['name'];
    season = json['season'];
    tip = json['tip'];
    idx = json['idx'];
    info = json['info'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['youtube01'] = this.youtube01;
    data['image'] = this.image;
    data['kcal'] = this.kcal;
    data['youtube02'] = this.youtube02;
    data['youtube03'] = this.youtube03;
    data['effect'] = this.effect;
    data['keep'] = this.keep;
    data['name'] = this.name;
    data['season'] = this.season;
    data['tip'] = this.tip;
    data['idx'] = this.idx;
    data['info'] = this.info;
    return data;
  }
}
